#!/bin/bash

# CONTEXT: guest
# PURPOSE: adds the reddwarf host as an apt repo to get so that the guest can get the conf file for mysql

set -e
set -o xtrace

cat <<EOL >> /etc/apt/sources.list.d/reddwarf-source-host.list
deb http://10.0.0.1:8080/debian squeeze main
EOL
