#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install basic services and applications

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install apparmor-utils
#mytop policycoreutils sysstat ntp lvm2 xfsprogs xfsdump
