#!/bin/bash

# CONTEXT: guest
# PURPOSE: Add the guest image user that will own the reddwarf agent source.

set -e
set -o xtrace

if ! id -u ${GUEST_USERNAME} >/dev/null 2>&1; then
    echo "Adding ${GUEST_USERNAME} user"
    useradd -G admin -m ${GUEST_USERNAME} -s /bin/bash
    passwd ${GUEST_USERNAME} <<_EOF_
${GUEST_USERNAME}
${GUEST_USERNAME}
_EOF_
fi

