#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: take "staged" ssh keys (see extra-data.d/62-ssh-key) and put them in the GUEST_USERS home directory

set -e
set -o xtrace

source $_LIB/die

if [ -e "/tmp/in_target.d/ssh-authorized-keys" ]; then
    if ! [ -e "/home/${GUEST_USERNAME}/.ssh" ]; then
        sudo -Hiu ${GUEST_USERNAME} mkdir ~${GUEST_USERNAME}/.ssh/
    fi
    sudo -Hiu ${GUEST_USERNAME} dd of=~${GUEST_USERNAME}/.ssh/authorized_keys conv=notrunc if=/tmp/in_target.d/ssh-authorized-keys
    if ! [ -e "/home/${GUEST_USERNAME}/.ssh/id_rsa" ]; then
        sudo -Hiu ${GUEST_USERNAME} dd of=~${GUEST_USERNAME}/.ssh/id_rsa if=/tmp/in_target.d/id_rsa
        # perms have to be right on this file for ssh to work
        sudo -Hiu ${GUEST_USERNAME} chmod 600 ~${GUEST_USERNAME}/.ssh/id_rsa
        sudo -Hiu ${GUEST_USERNAME} dd of=~${GUEST_USERNAME}/.ssh/id_rsa.pub if=/tmp/in_target.d/id_rsa.pub
    fi
else
    die "SSH Keys were not staged by host"
fi
